print("without if/else")
print("[func for i in iterator]")
print("example: [i**2 for i in range(3)] ")
print([i ** 2 for i in range(3)])
print("-" * 100)
print("with if")
print("[func for i in iterator if condition]")
print("example: [i ** 2 for i in range(5) if i % 2 == 0]")
print([i ** 2 for i in range(5) if i % 2 == 0])
print("-" * 100)
print("with if and else")
print("[func1 if condition else func2 for i in iterator]")
print("example: [i ** 3 if i % 3 == 0 else i ** 2 for i in range(10)]")
print([i ** 3 if i % 3 == 0 else i ** 2 for i in range(10)])
print("-" * 100)
print("with if and elif")
print("[func1 if condition1 else func2 if condition2 else func3 for i in iterator]")
print("example: [i**2 if i%4==2 else i**3 if i%4==3 else i**4 for i in range(10)]")
print([i ** 2 if i % 4 == 2 else i ** 3 if i % 4 == 3 else i ** 4 for i in range(10)])
